name: flutter_twitter
description: A new Flutter project.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  equatable: ^2.0.0
  intl: ^0.19.0


dev_dependencies:
  bloc_test: ^9.1.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0
  patrol: ^3.11.2
  test: ^1.25.7

flutter:
  uses-material-design: true

patrol:
  app_name: Cubitter
  android:
    package_name: com.example.flutter_twitter
